language: go
sudo: false

go:
  - "1.15"
  - "1.16"
  - "1.17"
  - "tip"

before_install:
  - export PATH=$HOME/gopath/bin:$PATH
  - go get github.com/mattn/goveralls

script:
  - go test -race ./...
  - go test -coverprofile=coverage.out -cover ./...
  - goveralls -coverprofile=coverage.out -service=travis-ci -ignore=examples/*/*.go,examples/*/*/*.go,testutil/*.go

matrix:
  allow_failures:
   - go: tip

git:
  depth: 10

env:
  - GO111MODULE=on
